### ISSUE TITLE
Are you interessted in german text translations?

### ISSUE THREAD

**Issue by masseelch** [CivPlayersLeague/Better-Balanced-Game#17]
Hi,

we recently started a new game with your mod in our Civ group. We all do play the german version of the game. The changes made have no effect on the german texts, which led to some confusion.

We are happy to contribute a german translation of the changes (and keep them up to date) if you add them to the mod.

Thanks for the awesome work.

**Comment by masseelch** [comment]
Are translations for the values below [this line](https://github.com/CivPlayersLeague/Better-Balanced-Game/blob/c6a1824937ba146657fe6501d255a09125d30a76/lang/english.xml#L740) necessary?

**Comment by codenaugh** [comment]
Yes, you can submit a pull request with your new file. 

Instructions to translate:
1. Change the language tag to "de_DE"
2. Only translate what's between the \<Text> and \</Text> tags, but nothing inside of square or curly brackets; Anything inside those brackets {} [] shall remain in english

**Comment by masseelch** [comment]
> Yes, you can submit a pull request with your new file.

Will take a couple days, though.

> Instructions to translate:
> 
> 1. Change the language tag to "de_DE"
> 2. Only translate what's between the <Text> and </Text> tags, but nothing inside of square or curly brackets; Anything inside those brackets {} [] shall remain in english.

Yeah I figured 😉

I already added the file to the `.modinfo`.
