### ISSUE TITLE
Lenses (and other controls) not working

### ISSUE THREAD

**Issue by NinkuFlavius** [CivPlayersLeague/Better-Balanced-Game#19]
Civ6 version: 1.0.6.9 (521158), Epic Store
Expansions: Gathering Storm
BBG version: 3.16.6

Whats wrong: Selecting any of the lenses does not actually update the tiles with colors. Other controls (on the bottom left) like search also dont work.
Not sure if there's some common troubleshooting steps I am missing.

![MissingLens](https://user-images.githubusercontent.com/16955152/97772834-e83d8900-1b07-11eb-973e-42b48fb8e4a1.PNG)
![Mod](https://user-images.githubusercontent.com/16955152/97772838-eb387980-1b07-11eb-8a9f-5ffc4c175888.PNG)

**Comment by codenaugh** [comment]
Hello, that doesn't look like my BBG mod. Mine looks like so: 
![image](https://user-images.githubusercontent.com/5515905/97787022-c88c7c00-1b6c-11eb-8842-02b629ce2475.png)

**Comment by NinkuFlavius** [comment]
Thanks for the clarification. I downloaded this from the [official steam page](https://steamcommunity.com/sharedfiles/filedetails/?id=1368312893) (by following instructions from [here](https://gamerant.com/civilization-6-mods-epic-games-store-civ-egs-install-how/)). 
Directly downloading from github and putting it in the right folder worked.
